logo: https://raw.githubusercontent.com/TukuToi/Zero-Tracking-Policy/main/img/TukuToi%20Zero%20Tracking%20Badge.png
title: TukuToi Zero Tracking Policy
description: TukuToi Zero Tracking and Full Privacy Badge is granted to any Online Instance following the TukuToi Zero Tracking Policy
theme: jekyll-theme-minimal

